/*
 * DIO_conf.h
 *
 * Created: 9/11/2019 8:57:14 AM
 *  Author: Louda
 */ 


#ifndef DIO_CONF_H_
#define DIO_CONF_H_


#define PORTA_PIN0_INITVAL    LOW
#define PORTA_PIN1_INITVAL    LOW
#define PORTA_PIN2_INITVAL    LOW
#define PORTA_PIN3_INITVAL    LOW
#define PORTA_PIN4_INITVAL    LOW
#define PORTA_PIN5_INITVAL    LOW
#define PORTA_PIN6_INITVAL    LOW
#define PORTA_PIN7_INITVAL    LOW

#define PORTB_PIN0_INITVAL    LOW
#define PORTB_PIN1_INITVAL    LOW
#define PORTB_PIN2_INITVAL    LOW
#define PORTB_PIN3_INITVAL    LOW
#define PORTB_PIN4_INITVAL    LOW
#define PORTB_PIN5_INITVAL    LOW
#define PORTB_PIN6_INITVAL    LOW
#define PORTB_PIN7_INITVAL    LOW

#define PORTC_PIN0_INITVAL    LOW
#define PORTC_PIN1_INITVAL    LOW
#define PORTC_PIN2_INITVAL    LOW
#define PORTC_PIN3_INITVAL    LOW
#define PORTC_PIN4_INITVAL    LOW
#define PORTC_PIN5_INITVAL    LOW
#define PORTC_PIN6_INITVAL    LOW
#define PORTC_PIN7_INITVAL    LOW

#define PORTD_PIN0_INITVAL    LOW
#define PORTD_PIN1_INITVAL    LOW
#define PORTD_PIN2_INITVAL    LOW
#define PORTD_PIN3_INITVAL    LOW
#define PORTD_PIN4_INITVAL    LOW
#define PORTD_PIN5_INITVAL    LOW
#define PORTD_PIN6_INITVAL    LOW
#define PORTD_PIN7_INITVAL    LOW



#define PORTA_PIN0_INITDIR    IN
#define PORTA_PIN1_INITDIR    IN
#define PORTA_PIN2_INITDIR    IN
#define PORTA_PIN3_INITDIR    IN
#define PORTA_PIN4_INITDIR    IN
#define PORTA_PIN5_INITDIR    IN
#define PORTA_PIN6_INITDIR    IN
#define PORTA_PIN7_INITDIR    IN

#define PORTB_PIN0_INITDIR    IN
#define PORTB_PIN1_INITDIR    IN
#define PORTB_PIN2_INITDIR    IN
#define PORTB_PIN3_INITDIR    IN
#define PORTB_PIN4_INITDIR    IN
#define PORTB_PIN5_INITDIR    IN
#define PORTB_PIN6_INITDIR    IN
#define PORTB_PIN7_INITDIR    IN

#define PORTC_PIN0_INITDIR    OUT
#define PORTC_PIN1_INITDIR    OUT
#define PORTC_PIN2_INITDIR    OUT
#define PORTC_PIN3_INITDIR    OUT
#define PORTC_PIN4_INITDIR    OUT
#define PORTC_PIN5_INITDIR    OUT
#define PORTC_PIN6_INITDIR    OUT
#define PORTC_PIN7_INITDIR    OUT

#define PORTD_PIN0_INITDIR    IN
#define PORTD_PIN1_INITDIR    IN
#define PORTD_PIN2_INITDIR    IN
#define PORTD_PIN3_INITDIR    IN
#define PORTD_PIN4_INITDIR    IN
#define PORTD_PIN5_INITDIR    IN
#define PORTD_PIN6_INITDIR    IN
#define PORTD_PIN7_INITDIR    IN




#endif /* DIO_CONF_H_ */