
#include "timer.h"

static void (*TIMER_0_OVF_ISR)(void)  = '\0';
static void (*TIMER_0_COMP_ISR)(void) = '\0';
static void (*TIMER_2_OVF_ISR)(void)  = '\0';
static void (*TIMER_2_COMP_ISR)(void) = '\0';


void Timer_Init(void)
{
	#if (TIMER_0_INIT == TIMER_INIT)	
		/*** SET TIMER0 MODE ***/
		#if (TIMER_0_MODE == TIMER_MODE_NORMAL)
			CLR_BITS(TIMER_TCCR0 , TIMER_TCCR0_WGM00 | TIMER_TCCR0_WGM01);		
		#elif (TIMER_0_MODE == TIMER_MODE_CTC)
			SET_BITS(TIMER_TCCR0 , TIMER_TCCR0_WGM01);
			CLR_BITS(TIMER_TCCR0 , TIMER_TCCR0_WGM00);
			/*** SET OC0 MODE ***/
			#if   (TIMER_0_OC0_MODE == TIMER_OCn_NON_PWM_DISCONNECT) 
				CLR_BITS(TIMER_TCCR0 , TIMER_TCCR0_COM00 | TIMER_TCCR0_COM01);
			#elif (TIMER_0_OC0_MODE == TIMER_OCn_NON_PWM_TOGGLE)
				SET_BITS(TIMER_TCCR0 , TIMER_TCCR0_COM00);
				CLR_BITS(TIMER_TCCR0 , TIMER_TCCR0_COM01);
			#elif (TIMER_0_OC0_MODE == TIMER_OCn_NON_PWM_CLEAR)
				SET_BITS(TIMER_TCCR0 , TIMER_TCCR0_COM01);
				CLR_BITS(TIMER_TCCR0 , TIMER_TCCR0_COM00);
			#elif (TIMER_0_OC0_MODE == TIMER_OCn_NON_PWM_SET)
				SET_BITS(TIMER_TCCR0 , TIMER_TCCR0_COM00 | TIMER_TCCR0_COM01);
			#endif	
		#elif (TIMER_0_MODE == TIMER_MODE_FAST_PWM)
			SET_BITS(TIMER_TCCR0 , TIMER_TCCR0_WGM00 | TIMER_TCCR0_WGM01);
			/*** SET OC0 MODE ***/
			#if   (TIMER_0_OC0_MODE == TIMER_OCn_FAST_PWM_DISCONNECT) 
				CLR_BITS(TIMER_TCCR0 , TIMER_TCCR0_COM00 | TIMER_TCCR0_COM01);
			#elif (TIMER_0_OC0_MODE == TIMER_OCn_FAST_PWM_SET_AT_TOP)
				SET_BITS(TIMER_TCCR0 , TIMER_TCCR0_COM01);
				CLR_BITS(TIMER_TCCR0 , TIMER_TCCR0_COM00);
			#elif (TIMER_0_OC0_MODE == TIMER_OCn_FAST_PWM_CLEAR_AT_TOP)
				SET_BITS(TIMER_TCCR0 , TIMER_TCCR0_COM00 | TIMER_TCCR0_COM01);
			#endif
		#elif (TIMER_0_MODE == TIMER_MODE_PHASE_CORRECT_PWM)
			SET_BITS(TIMER_TCCR0 , TIMER_TCCR0_WGM00);
			CLR_BITS(TIMER_TCCR0 , TIMER_TCCR0_WGM01);
			/*** SET OC0 MODE ***/
			#if (TIMER_0_OC0_MODE == TIMER_OCn_PHASE_CORRECT_PWM_DISCONNECT)
				CLR_BITS(TIMER_TCCR0 , TIMER_TCCR0_COM00 | TIMER_TCCR0_COM01);
			#elif (TIMER_0_OC0_MODE == TIMER_OCn_PHASE_CORRECT_PWM_CLEAR_AT_UP_COUNT)
				SET_BITS(TIMER_TCCR0 , TIMER_TCCR0_COM01);
				CLR_BITS(TIMER_TCCR0 , TIMER_TCCR0_COM00);
			#elif (TIMER_0_OC0_MODE == TIMER_OCn_PHASE_CORRECT_PWM_SET_AT_UP_COUNT)
				SET_BITS(TIMER_TCCR0 , TIMER_TCCR0_COM00 | TIMER_TCCR0_COM01);
			#endif
		#endif
		
		
		/*** CLOCK SELECT for timer 0 ***/
		#if (TIMER_0_PRESCALER == TIMER_PRESCALER_1)
			SET_BITS(TIMER_TCCR0 , TIMER_TCCR0_CS00);
			CLR_BITS(TIMER_TCCR0 , TIMER_TCCR0_CS01 | TIMER_TCCR0_CS02);		   
		#elif (TIMER_0_PRESCALER == TIMER_PRESCALER_8)
			SET_BITS(TIMER_TCCR0 , TIMER_TCCR0_CS01);
			CLR_BITS(TIMER_TCCR0 , TIMER_TCCR0_CS00 | TIMER_TCCR0_CS02);
		#elif (TIMER_0_PRESCALER == TIMER_PRESCALER_32)
			SET_BITS(TIMER_TCCR0 , TIMER_TCCR0_CS00 | TIMER_TCCR0_CS01);
			CLR_BITS(TIMER_TCCR0 , TIMER_TCCR0_CS02);			   
		#elif (TIMER_0_PRESCALER == TIMER_PRESCALER_64)
			SET_BITS(TIMER_TCCR0 , TIMER_TCCR0_CS00 | TIMER_TCCR0_CS01);
			CLR_BITS(TIMER_TCCR0 , TIMER_TCCR0_CS02);
		#elif (TIMER_0_PRESCALER == TIMER_PRESCALER_128)
			SET_BITS(TIMER_TCCR0 , TIMER_TCCR0_CS00 | TIMER_TCCR0_CS02);
			CLR_BITS(TIMER_TCCR0 , TIMER_TCCR0_CS01);	
		#elif (TIMER_0_PRESCALER == TIMER_PRESCALER_256)
			SET_BITS(TIMER_TCCR0 , TIMER_TCCR0_CS02);
			CLR_BITS(TIMER_TCCR0 , TIMER_TCCR0_CS00 | TIMER_TCCR0_CS01);		
		#elif (TIMER_0_PRESCALER == TIMER_PRESCALER_1024)
			SET_BITS(TIMER_TCCR0 , TIMER_TCCR0_CS00 | TIMER_TCCR0_CS02);
			CLR_BITS(TIMER_TCCR0 , TIMER_TCCR0_CS01);	
		#endif		
	#endif
	
	
	#if (TIMER_2_INIT == TIMER_INIT)
		/*** SET TIMER2 MODE ***/
		#if (TIMER_2_MODE == TIMER_MODE_NORMAL)
			CLR_BITS(TIMER_TCCR2 , TIMER_TCCR2_WGM20 | TIMER_TCCR2_WGM21);
		#elif (TIMER_2_MODE == TIMER_MODE_CTC)
			SET_BITS(TIMER_TCCR2 , TIMER_TCCR2_WGM21);
			CLR_BITS(TIMER_TCCR2 , TIMER_TCCR2_WGM20);
			/*** SET OC0 MODE ***/
			#if   (TIMER_2_OC2_MODE == TIMER_OCn_NON_PWM_DISCONNECT) 
				CLR_BITS(TIMER_TCCR2 , TIMER_TCCR2_COM20 | TIMER_TCCR2_COM21);
			#elif (TIMER_2_OC2_MODE == TIMER_OCn_NON_PWM_TOGGLE)
				SET_BITS(TIMER_TCCR2 , TIMER_TCCR2_COM20);
				CLR_BITS(TIMER_TCCR2 , TIMER_TCCR2_COM21);
			#elif (TIMER_2_OC2_MODE == TIMER_OCn_NON_PWM_CLEAR)
				SET_BITS(TIMER_TCCR2 , TIMER_TCCR2_COM21);
				CLR_BITS(TIMER_TCCR2 , TIMER_TCCR2_COM20);
			#elif (TIMER_2_OC2_MODE == TIMER_OCn_NON_PWM_SET)
				SET_BITS(TIMER_TCCR2 , TIMER_TCCR2_COM20 | TIMER_TCCR2_COM21);
			#endif
		#elif (TIMER_2_MODE == TIMER_MODE_FAST_PWM)
			SET_BITS(TIMER_TCCR2 , TIMER_TCCR2_WGM20 | TIMER_TCCR2_WGM21);
			/*** SET OC0 MODE ***/
			#if   (TIMER_2_OC2_MODE == TIMER_OCn_FAST_PWM_DISCONNECT) 
				CLR_BITS(TIMER_TCCR2 , TIMER_TCCR2_COM20 | TIMER_TCCR2_COM21);
			#elif (TIMER_2_OC2_MODE == TIMER_OCn_FAST_PWM_SET_AT_TOP)
				SET_BITS(TIMER_TCCR2 , TIMER_TCCR2_COM21);
				CLR_BITS(TIMER_TCCR2 , TIMER_TCCR2_COM20);
			#elif (TIMER_2_OC2_MODE == TIMER_OCn_FAST_PWM_CLEAR_AT_TOP)
				SET_BITS(TIMER_TCCR2 , TIMER_TCCR2_COM20 | TIMER_TCCR2_COM21);
			#endif
		#elif (TIMER_2_MODE == TIMER_MODE_PHASE_CORRECT_PWM)
			SET_BITS(TIMER_TCCR2 , TIMER_TCCR2_WGM20);
			CLR_BITS(TIMER_TCCR2 , TIMER_TCCR2_WGM21);
			/*** SET OC0 MODE ***/
			#if (TIMER_2_OC2_MODE == TIMER_OCn_PHASE_CORRECT_PWM_DISCONNECT)
				CLR_BITS(TIMER_TCCR2 , TIMER_TCCR2_COM20 | TIMER_TCCR2_COM21);
			#elif (TIMER_2_OC2_MODE == TIMER_OCn_PHASE_CORRECT_PWM_CLEAR_AT_UP_COUNT)
				SET_BITS(TIMER_TCCR2 , TIMER_TCCR2_COM21);
				CLR_BITS(TIMER_TCCR2 , TIMER_TCCR2_COM20);
			#elif (TIMER_2_OC2_MODE == TIMER_OCn_PHASE_CORRECT_PWM_SET_AT_UP_COUNT)
				SET_BITS(TIMER_TCCR2 , TIMER_TCCR2_COM20 | TIMER_TCCR2_COM21);
			#endif
		#endif
		

		/*** CLOCK SELECT for timer 2 ***/
		#if (TIMER_2_PRESCALER == TIMER_PRESCALER_1)
			SET_BITS(TIMER_TCCR2 , TIMER_TCCR2_CS20);
			CLR_BITS(TIMER_TCCR2 , TIMER_TCCR2_CS21 | TIMER_TCCR2_CS22);		
		#elif (TIMER_2_PRESCALER == TIMER_PRESCALER_8)
			SET_BITS(TIMER_TCCR2 , TIMER_TCCR2_CS21);
			CLR_BITS(TIMER_TCCR2 , TIMER_TCCR2_CS20 | TIMER_TCCR2_CS22);
		#elif (TIMER_2_PRESCALER == TIMER_PRESCALER_32)
			SET_BITS(TIMER_TCCR2 , TIMER_TCCR2_CS20 | TIMER_TCCR2_CS21);
			CLR_BITS(TIMER_TCCR2 , TIMER_TCCR2_CS22);			
		#elif (TIMER_2_PRESCALER == TIMER_PRESCALER_64)
			SET_BITS(TIMER_TCCR2 , TIMER_TCCR2_CS20 | TIMER_TCCR2_CS21);
			CLR_BITS(TIMER_TCCR2 , TIMER_TCCR2_CS22);
		#elif (TIMER_2_PRESCALER == TIMER_PRESCALER_128)
			SET_BITS(TIMER_TCCR2 , TIMER_TCCR2_CS20 | TIMER_TCCR2_CS22);
			CLR_BITS(TIMER_TCCR2 , TIMER_TCCR2_CS21);
		#elif (TIMER_2_PRESCALER == TIMER_PRESCALER_256)
			SET_BITS(TIMER_TCCR2 , TIMER_TCCR2_CS22);
			CLR_BITS(TIMER_TCCR2 , TIMER_TCCR2_CS20 | TIMER_TCCR2_CS21);		
		#elif (TIMER_2_PRESCALER == TIMER_PRESCALER_1024)
			SET_BITS(TIMER_TCCR2 , TIMER_TCCR2_CS20 | TIMER_TCCR2_CS22);
			CLR_BITS(TIMER_TCCR2 , TIMER_TCCR2_CS21);	
		#endif
		
	#endif

    /*** Enable the interrupts ***/
	/*SET_BITS(TIMER_TIMSK , TIMER_TIMSK_TOIE0 | TIMER_TIMSK_OCIE0 | TIMER_TIMSK_TOIE2 | TIMER_TIMSK_OCIE2);*/

}



/*
interrupt could be 
	TIMER_TIMSK_TOIE0 , TIMER_TIMSK_OCIE0 , TIMER_TIMSK_TOIE2 |, TIMER_TIMSK_OCIE2
*/
void Timer_EnableInterrupt(u8 interrupt)
{

	SET_BITS(TIMER_TIMSK , interrupt);
	
}

void Timer_DisableInterrupt(u8 interrupt)
{

	CLR_BITS(TIMER_TIMSK , interrupt);
	
}


void Timer_LoadTCNT(u8 timer ,u8 Local_Value)
{
	switch (timer)
	{
		case(TIMER_0):
			TIMER_TCNT0 = Local_Value;
			break;
			
		case(TIMER_2):
			TIMER_TCNT2 = Local_Value;
			break;
		
		default:
			break;
	}
    
}

void Timer_LoadOCR(u8 timer ,u8 Local_Value)
{
	switch (timer)
	{
		case(TIMER_0):
			TIMER_OCR0 = Local_Value;
			break;
			
		case(TIMER_2):
			TIMER_OCR2 = Local_Value;
			break;
		
		default:
			break;
	}
    
}


void Pwm_SetDutyCycle(u8 timer ,u8 DutyCycle)
{
	static f32 temp_1 = 0;
	
	temp_1 = ((f32)DutyCycle)/100;
	temp_1 *= 255;
	
	Timer_LoadOCR(timer,temp_1);
	
}



void Pwm_Volt2DutyCycle(u8 timer ,f32 volt)
{
	static f32 temp_1 = 0;
	static f32  DutyCycle = 0;
	
	temp_1	  = volt / 5;
	DutyCycle = temp_1 * 100;
	
	Pwm_SetDutyCycle(timer , DutyCycle);
	
}


void Timer_SetCompareMatch_ISR(u8 timer ,void (*Local_COMP_ISR)(void))
{
	switch (timer)
	{
		case (TIMER_0):
			TIMER_0_COMP_ISR = Local_COMP_ISR;
		break;
		
		case (TIMER_2):
			TIMER_2_COMP_ISR = Local_COMP_ISR;
		break;
		
		default:
			break;
	}
	
}

void Timer_SetOverFlow_ISR(u8 timer ,void (*Local_OV_ISR)(void))
{
	switch (timer)
	{
		case (TIMER_0):
			TIMER_0_OVF_ISR = Local_OV_ISR;
		break;
		
		case (TIMER_2):
			TIMER_2_OVF_ISR = Local_OV_ISR;
		break;
		
		default:
			break;
	}
    
}
 
 ISR(TIMER0_OVF_vect)
 {
     TIMER_0_OVF_ISR();
 }

ISR(TIMER0_COMP_vect)
{
    TIMER_0_COMP_ISR();
}

 
 ISR(TIMER2_OVF_vect)
 {
     TIMER_2_OVF_ISR();
 }


ISR(TIMER2_COMP_vect)
{
    TIMER_2_COMP_ISR();
}




